# Do not add tabs, only spaces. Moved here in a file so some XML formatters won't break the launch file.
publish_period: 0.010
dxl_read_period: 0.010
dxl_write_period: 0.010
mobile_robot_config:                #<!--this values will be set when 'use_cmd_vel' is true-->
  seperation_between_wheels: 0.160  #<!--default value is set by reference of TB3-->
  radius_of_wheel: 0.033            #<!--default value is set by reference of TB3-->
