# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
zaxis:
  ID: 1
  # Torque_Enable: 0
  # Velocity_limit: 120
  Profile_Velocity: 0 # Maximum 10?
  Return_Delay_Time: 0
  Min_Position_Limit: 0
  Max_Position_Limit: 4095
  Operating_Mode: 3 # Position control mode
 
xaxis:
  ID: 2
  Return_Delay_Time: 0
  Min_Position_Limit: 0
  Max_Position_Limit: 1365
  Operating_Mode: 3 # Position control mode
  #Profile_Velocity: 100
yaxis:
  ID: 3
  Return_Delay_Time: 0
  Min_Position_Limit: 0
  Max_Position_Limit: 1535
  Operating_Mode: 3 # Position control mode
  #Profile_Velocity: 100
