# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
zaxis:
  ID: 1
  Return_Delay_Time: 0
xaxis:
  ID: 2
  Return_Delay_Time: 0
yaxis:
  ID: 3
  Return_Delay_Time: 0
