#!/usr/bin/env python

import os
import rospkg
import rospy
from python_qt_binding import *
from PyQt5 import *
from PyQt5.QtCore import pyqtSlot
from dynamixel_workbench_msgs.srv import *
from dynamixel_workbench_msgs.msg import *
from functools import partial
from rqt_gui.main import Main
from std_msgs.msg import String
import sys
# from main_control import *
# from manual_control import *


# start_joy = True

if __name__ == "__main__":


    rospy.init_node('main_node', anonymous=True)
    # main_node() class does not exist anymore
    
    # test = main_node()
    # if (start_joy):
    #     mc_node = ManualControl('mc_xbox')
    #     pass


    rospy.spin()
